// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTk8osVZm4Clf4IqhMNaFoRbbfBUhJGsI',
    appId: '1:620286182402:web:00b6316578795055c9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    authDomain: 'fir-8995d.firebaseapp.com',
    storageBucket: 'fir-8995d.firebasestorage.app',
    measurementId: 'G-LGB0GKKN5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAynMElq_wHif3rJCOzjbFD18NIbLwwRVQ',
    appId: '1:620286182402:android:71115b295f268a65c9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    storageBucket: 'fir-8995d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK6JEFiBhpjFiQ5PBQxz4iVesi7ust8lY',
    appId: '1:620286182402:ios:7976d31c3b9c3727c9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    storageBucket: 'fir-8995d.firebasestorage.app',
    iosBundleId: 'com.example.thekrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK6JEFiBhpjFiQ5PBQxz4iVesi7ust8lY',
    appId: '1:620286182402:ios:7976d31c3b9c3727c9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    storageBucket: 'fir-8995d.firebasestorage.app',
    iosBundleId: 'com.example.thekrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWhneBogmnL88ejczaHrBPLzWXKBimGl0',
    appId: '1:620286182402:web:cfba5e31a81e5b64c9131b',
    messagingSenderId: '620286182402',
    projectId: 'fir-8995d',
    authDomain: 'fir-8995d.firebaseapp.com',
    storageBucket: 'fir-8995d.firebasestorage.app',
    measurementId: 'G-CFF07CYZ7T',
  );
}
