# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Internal Track"
  lane :deploy do
    # Find the AAB file dynamically
    aab_files = Dir.glob("../**/app-release.aab")
    
    if aab_files.empty?
      UI.user_error!("No AAB file found in the project")
    end
    
    aab_path = aab_files.first
    UI.message("Found AAB file at: #{aab_path}")
    UI.success("AAB file size: #{File.size(aab_path)} bytes")

    upload_to_play_store(
      track: "alpha",
      aab: aab_path,
      json_key: "fastlane/play-store-service-account.json",
      package_name: "com.zaid.thekr_app",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
